version: '2'
services:
    torrent-sync:
        image: kurron/docker-bittorrent-sync:latest
        container_name: bt-sync
        restart: always
        network_mode: host
        volumes:
        - /media/storage/bt-sync:/bt-sync
    plex:
        image: timhaak/plex:latest
        container_name: plex
        restart: always
        network_mode: host
        volumes:
        - /media/storage/plex-config:/config
        - /media/storage/plex:/data:ro
        environment:
            SKIP_CHOWN_CONFIG: "TRUE"
    consul:
        image: consul:latest
        container_name: consul
        restart: always
        network_mode: host
        volumes:
        - ./consul:/consul/config:ro
        - /media/storage/consul:/consul/data:rw
        command: consul agent -config-dir /consul/config
    transmission:
        image: dperson/transmission
        container_name: transmission
        restart: always
        network_mode: host
        environment:
            TRUSER: admin
            TRPASSWD: admin
